### ISSUE TITLE
Take DataView concept into use

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-checkbox-flow#141]
Based on vaadin/flow#8267, introduce the `ListDataView<T>` and `HasListDataView<T>` to `CheckboxGroup`. Try to see what parts can be pulled out to reusing with `flow-data` and be shared with other in-memory-only components or with Grid vaadin/vaadin-grid-flow#965.
The work should be pushed to `feature/dataprovider` branch and use Flow `3.2.dataprovider-SNAPSHOT`.

**Comment by mshabarov** [comment]
@pleku , just wanted to clarify something: do we need to create a `CheckboxGroupDataView` with a specific API? Perhaps there would be something in `CheckboxGroup` we may expose via this interface.

> Try to see what parts can be pulled out to reusing with flow-data and be shared with other in-memory-only components or with Grid

Does this mean in practice that ListDataView would probably be extended with some extra methods from existing DataProvider interfaces/classes?
