### ISSUE TITLE
Create a prototype of using DataView API with CheckboxGroup

### ISSUE THREAD

**Issue by mshabarov** [vaadin/vaadin-checkbox-flow#142]
### Acceptance criteria:
- Use DataView API from vaadin/flow#8267 in `feature/dataprovider` branch and apply it to Vaadin CheckboxGroup component.
- Validate the proposed design for this common used non-lazy component.

**Comment by pleku** [comment]
Closing due to misunderstanding, duplicate of https://github.com/vaadin/vaadin-checkbox-flow/issues/141
