### ISSUE TITLE
Nonsense initial value change event

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-checkbox-flow#22]
```
Checkbox checkbox = new Checkbox("Checkbox label");
System.out.println("Checkbox default is " + checkbox.getValue());
checkbox.addValueChangeListener(e -> {
	System.out.println("Checkbox value changed from '" + e.getOldValue()
	+ "' to '" + e.getValue() + "'");
});
add(checkbox);
```

Expected output:
```
Checkbox default is false
```

Actual output:
```
Checkbox default is false
Checkbox value changed from 'null' to 'false'
```

**Comment by oluwasayo** [comment]
The “nonsense” change also seems to come from the client even if you set the `initialValue` when instantiating the checkbox.

Code:
```Checkbox check = new Checkbox("My box", false);```

Log:
```TRIGGERED! From null TO false from client```

**Comment by oluwasayo** [comment]
If you set an `initialValue` of `true` when instantiating the checkbox then you get the following output:
```TRIGGERED! From true TO false from client ```

**Comment by ZheSun88** [comment]
we realize that this issue is quite related to https://github.com/vaadin/flow/issues/3350. so after that has been fixed, we are going to verify on this issue. 

a workaround can be used for temporary fix is 
```
@Override
    public Registration addValueChangeListener(
            ValueChangeListener<Checkbox, Boolean> listener) {
        // TODO Auto-generated method stub
        return super.addValueChangeListener(e -> {
            if (e.getValue() != null && !e.getValue().equals(e.getOldValue())
                    || e.getValue() == null && e.getOldValue() != null) {
                listener.onComponentEvent(e);
            }
        });
    }
```
Bakery has using this. but this issue can affect all the other components which has a setValue and valueChangeEvent()
