### ISSUE TITLE
CheckBox fails when value is set to 'true' on server side

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-checkbox-flow#3]
@tmattsso commented on [Thu Sep 21 2017](https://github.com/vaadin/flow/issues/2459)

even though the value is sent as true to the client, the client ignores this, sets the value to false, and produces an RPC call. To reproduce:

```
final Checkbox cb = new Checkbox("asd");
cb.setValue(true);
cb.addValueChangeListener(e -> System.out.println("asdad"));
add(cb);
```

---

@pleku commented on [Mon Sep 25 2017](https://github.com/vaadin/flow/issues/2459#issuecomment-331864699)

Up for investigation on whether or not this is a trivial thing and escalate if necessary

**Comment by pleku** [comment]
There is a test for this now in Checkbox that verifies that initial `true` value works.
