### ISSUE TITLE
setRequiredIndicatorVisible(boolean) method don't work

### ISSUE THREAD

**Issue by mstahv** [vaadin/vaadin-checkbox-flow#51]
The required indicator don't become visible when using setRequiredIndicatorVisible method, like it does with other fields.

A code to reproduce:

    Checkbox acceptTerms = new Checkbox("I accept the terms & privacy policy [1]");
    acceptTerms.setRequiredIndicatorVisible(true);

**Comment by pleku** [comment]
It should throw `UnsupportedOperationException` instead, but somehow the method override has been removed.

This is blocked by 
https://github.com/vaadin/vaadin-checkbox/pull/85
