### ISSUE TITLE
Use Checkbox for Remember Me (Spring Security)

### ISSUE THREAD

**Issue by TheSilentHorizon** [vaadin/vaadin-checkbox-flow#55]
So Spring Security has this pretty neat remember me implementation i want use. In order to do that, I need to set the name attribute of the input checkbox inside the component to "remember-me" or something else. Is there a way to achieve this? Or do I need to create a custom checkbox for thisß

**Comment by ZheSun88** [comment]
Flow repo is only taking bug-report. For asking questions and ideas, I would like to suggest you to go [vaadin/forum](https://vaadin.com/forum), where you will get more proper help. 

This issue will be closed. Thanks for your cooperation.
