### ISSUE TITLE
Once https://github.com/vaadin/vaadin-text-field-flow/issues/4 is fixed checkbox's setValue behaves incorrectly

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-checkbox-flow#6]
See http://localhost:8080/vaadin-checkbox (with fix for https://github.com/vaadin/vaadin-text-field-flow/issues/4).

In the indeterminate checkbox:
- set value ( click on it so it becomes checked).
- Click "Reset".

The expected: 
- checkbox becomes indeterminate
- it has no `checked` attribute

The result is:
- checkbox becomes indeterminate
- but it still has `checked` attribute

The `checked` attribute is removed only after the second click.

**Comment by gilberto-torrezan** [comment]
Blocked by https://github.com/vaadin/vaadin-checkbox/issues/42

**Comment by gilberto-torrezan** [comment]
The change from the elements team was reverted, since it conflicts with the native behavior: https://github.com/vaadin/vaadin-checkbox/issues/42

So we need to provide a solution for this problem on the Flow side.

**Comment by pleku** [comment]
Has been fixed by having the checkbox work the same way on both client & server and follow the html5 standard.
