### ISSUE TITLE
Add CheckboxGroup support

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-checkbox-flow#62]
CheckboxGroup has been released with `vaadin-checkbox` 2.2.0.alpha3. 
Should be added here also.

And add a demo to showcase the theme variants

**Comment by denis-anisimov** [comment]
Combobox group is blocked by this bug: https://github.com/vaadin/vaadin-combo-box/issues/687

As a result we don't get any update about value change from the client side to the server side.
So the main functionality of the component is broken.
I will proceed with other features for the group component but I won't be able to create a PR without fix for the bug on the web component side.

**Comment by ZheSun88** [comment]
@denis-anisimov Do you mean checkboxGroup? and the linked the issue is wrong..

**Comment by denis-anisimov** [comment]
Yes, checkbox group.
Every every time I confuses combobox and checkbox.
Corrected, thanks.
