### ISSUE TITLE
Cannot set initial value of @Id mapped checkbox

### ISSUE THREAD

**Issue by Legioth** [vaadin/vaadin-checkbox-flow#70]
`myCheckbox.setValue(true)` has not effect if done in the constructor of a `PolymerTemplate` class. Toggling the value later, e.g. through a button click listener works as expected. Setting the initial value also works if the CheckBox is created without `@Id` and added to a layout in the conventional way.

**Comment by denis-anisimov** [comment]
Which version?
I remember there are already a couple of ticket with the same description.
It was fixed a week ago.

**Comment by denis-anisimov** [comment]
https://github.com/vaadin/flow/issues/4304
https://github.com/vaadin/vaadin-checkbox-flow/issues/60

Please check in the latest version and reopen if it's still there.

**Comment by Legioth** [comment]
Confirmed that it works with the latest SNAPSHOT version.
