### ISSUE TITLE
CheckBoxGroup deselect not working at first click

### ISSUE THREAD

**Issue by Fr33z3m4n** [vaadin/vaadin-checkbox-flow#83]
If you want to deactivate a checkbox that has been activated with SetValue, the status will not be changed on the first click.

Example with DemoView
public class CheckboxGroupView extends DemoView {
        ....
        private void addBasicFeatures() {
              Div message = new Div();
              // begin-source-example
             // source-example-heading: Basic checkbox group
            CheckboxGroup<String> group = new CheckboxGroup<>();
            group.setItems("foo", "bar", "baz");
           group.setValue(Sets.newHashSet("bar"));
           ....
    }
}

![2019-01-07-15-39-31](https://thumbs.gfycat.com/SpiritedDisguisedGraysquirrel-size_restricted.gif 
)

**Comment by Feuerwerk** [comment]
I have nearly the same problem. When you update Items/DataProvider and Selection in one step, the updated selection don't propagated to the individual checkboxes.

Given the code:
CheckboxGroup group = new CheckboxGroup<>();
group.setItems("foo", "bar", "baz");
group.setValue(Sets.newHashSet("bar"));

you have to run the following statement to fix the update problem:
UI.getCurrent().getPage().executeJavaScript("$0._updateValue($0.value, $0.value.splices);", group.getElement());

**Comment by Feuerwerk** [comment]
Yeah you're right. What i posted before was a partially fix for the problem that the selection don't appear on the client. The following line will fix your problem with checkbox selection don't disappear:

UI.getCurrent().getPage().executeJavaScript("$0._addCheckboxToValue = function(value) { const update = $0.value.slice(0); if (update.indexOf(value) == -1) update.push(value); $0.value = update; };", group.getElement());

**Comment by pekam** [comment]
This was fixed in the web component code and released in [vaadin-checkbox v2.2.8](https://github.com/vaadin/vaadin-checkbox/releases/tag/v2.2.8). It will be included in the next Vaadin 13 maintenance release and in Vaadin 14.
