### ISSUE TITLE
Calling dataProvider.refreshItem(item) will reset checkboxgroup

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-checkbox-flow#85]
Instead of just refreshing one item, CBG resets all items in https://github.com/vaadin/vaadin-checkbox-flow/blob/master/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java#L107

It should instead check for the type of the event fired by data provide, and if it is of type `DataChangeEvent.DataRefreshEvent` then update only the necessary item.

**Comment by campbellbartlett** [comment]
I've given this a shot. Are there any changes or extra tests that you would like me to implement?
