### ISSUE TITLE
Checkbox does not support Eager ValueChangeEvents

### ISSUE THREAD

**Issue by dve** [vaadin/vaadin-checkbox-flow#86]
When using checkbox in a grid header as a filter one need ValueChangeEvents imitatively when a users clicks on it. On TextFields one can use 'setValueChangeMode(ValueChangeMode valueChangeMode)' but 'com.vaadin.flow.data.value.HasValueChangeMode' is not implemented by Checkbox.

**Comment by Legioth** [comment]
Checkboxes are always eager. There is no `setValueChangeMode` since a lazy mode wouldn't make any sense.

At what point are you receiving value change events in your case?

**Comment by dve** [comment]
> At what point are you receiving value change events in your case?

There was no `ValueChangeListener` attached... - sorry for bothering you
