### ISSUE TITLE
Selection don't get updated

### ISSUE THREAD

**Issue by Feuerwerk** [vaadin/vaadin-checkbox-flow#89]
CheckboxGroup has a bug if you set the items (or a data provider) and the selection in one step e.g.

List<String> elements = .....;
group.setItems(elements);
group.select(elements);

In this case the selection within the browser is not visible but if you click on one of the checkboxes it will appear. This bug seems to be related to #83. I think the problem is within vaadin-checkbox-group.html (but only a problem for the Flow-Wrapper). At first _updateValue get called with the correct array of selected elements. This will update the selection state of the checkboxes accordingly. But then _observer will be notified about changed checkbox elements and THIS will update the selection on the client side, the server still assumes that all elements are selected.

**Comment by pekam** [comment]
This was fixed in the web component code and released in [vaadin-checkbox v2.2.8](https://github.com/vaadin/vaadin-checkbox/releases/tag/v2.2.8). It will be included in the next Vaadin 13 maintenance release and in Vaadin 14.
