### ISSUE TITLE
CheckBoxGroup demo is not shown on Vcom

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-checkbox-flow#95]
Only one demo page is shown in https://vaadin.com/components/vaadin-checkbox/java-examples

**Comment by ZheSun88** [comment]
actually, we have demos for the CheckboxGroup **(https://github.com/vaadin/vaadin-checkbox-flow/blob/master/vaadin-checkbox-flow-demo/src/main/java/com/vaadin/flow/component/checkbox/demo/CheckboxGroupView.java)** , 

but with the same reason as TextField/Password/TextArea, only one view can be shown there.

**Comment by web-padawan** [comment]
Demos have been merged, and then file name was changed in #130 so they are finally there.
