### ISSUE TITLE
Registered selection listener on CheckboxGroup is not invoked

### ISSUE THREAD

**Issue by gatanaso** [vaadin/vaadin-checkbox-flow#97]
### Description
Registered selection listener is not invoked.

### Expected outcome
Registered selection listener is invoked when the selection changes.

### Actual outcome
The registered event listener is not invoked.

### Steps to reproduce
1. Create a checkbox group and add items,
2. Add a selection listener via `addSelectionListener()`,
2. Add the checkbox group to the page.

```
        CheckboxGroup<String> checkboxGroup = new CheckboxGroup<>();
        checkboxGroup.setItems("Item 1", "Item 2", "Item 3", "Item 4", "Item 5");

        // event handler is not invoked
        checkboxGroup.addSelectionListener(event -> {
            Set<String> addedSelection = event.getAddedSelection();
            String selected = addedSelection.stream().collect(Collectors.joining(", "));
            Notification.show("selection listener: " + selected);
        });

        add(checkboxGroup);
```

### Reproducible example project (Vaadin Version 12.0.7)
[checkbox-group-demo.zip](https://github.com/vaadin/vaadin-checkbox-flow/files/2901677/checkbox-group-demo.zip)

**Comment by ZheSun88** [comment]
Hi @gatanaso , 
Thanks for reporting this. 
I did a quick analysis of your code provided here. In fact, you are misusing the `addSelectionListener` in this case. Based on what you have expected here, if i have understood correctly, you should use `addValueChangeListener` instead.
```java
checkboxGroup.addValueChangeListener(event -> {
            Set<String> addedSelection = event.getValue();
            String selected = addedSelection.stream().collect(Collectors.joining(", "));
            Notification.show("selection listener: " + selected);
        });
```

But i am going to keep this ticket here, as we should add some javadocs for the user to understand this. 

Thanks again.
